### ISSUE TITLE
_ keyword not working

### ISSUE THREAD

**Issue by razetime** [8Dion8/MAWP#1]
`%084W;|_` 
_ does not push length of stack as intended
```
chr:pos:stack
% : 1 : []
0 : 2 : [0]
8 : 3 : [0,8]
4 : 4 : [0,8,4]
W : 5 : [0,32]
; : 6 : [0]
| : 7 : [0,49,53]
_ : 8 : [0,49,53]
```

**Comment by kirisoraa** [comment]
@razetime Fixed. Waiting for the changes to update, once you see v1.01 try this link with your code and input. https://8dion8.github.io/?code=%25084W%3B%7C_.&input=15

**Comment by kirisoraa** [comment]
Also, for further issues please use [this](https://github.com/8Dion8/8Dion8.github.io) repository, as it is the one used for the online interpreter. This repository was the first draft of the language and was written in python
