### ISSUE TITLE
Multiline input?

### ISSUE THREAD

**Issue by kirisoraa** [8Dion8/MAWP#2]
My current suggestion for current functions is for them to take in one line of input at a time, with multiple calls needed for multiple lines. However, this might make the process of taking input of unknown height too complex. Please post any suggestions here! :)

**Comment by razetime** [comment]
Taking input of unknown height can be addresed by using the top of stack as a delimiter, possibly.

**Comment by kirisoraa** [comment]
@razetime possibly, but then still, you won't know if you've got all of the input. Maybe take input line by line, and then put a 0 once there are no lines left

**Comment by razetime** [comment]
ok, so basically read till you reach null or EOF, then add a 0. That would work well.

**Comment by kirisoraa** [comment]
@razetime I think the update should be live rn, there is a bug with newlines in the code editor though which I need to fix - each newline is 4 characters for some reason, so the bytecount won't be accurate with them
