### ISSUE TITLE
When is table of cohesion?

### ISSUE THREAD

**Issue by lyxal** [8Dion8/MAWP#4]
Asking because curious

**Comment by lyxal** [comment]
Wow such amazing issue.
@Lyxal you are great at github contributions

**Comment by lyxal** [comment]
> Wow such amazing issue.
> @Lyxal you are great at github contributions

Aw shucks. You're too diddly darn kind.

**Comment by lyxal** [comment]
> Asking because curious

about 10 minutes apparently

**Comment by lyxal** [comment]
> > Asking because curious
> 
> about 10 minutes apparently

@Lyxal what is your source?

**Comment by lyxal** [comment]
> > > Asking because curious
> > 
> > 
> > about 10 minutes apparently
> 
> @Lyxal what is your source?

The creator mentioned it in the MAWP discord

**Comment by lyxal** [comment]
> > > > Asking because curious
> > > 
> > > 
> > > about 10 minutes apparently
> > 
> > 
> > @Lyxal what is your source?
> 
> The creator mentioned it in the MAWP discord

Woah! There's a discord?!?

**Comment by lyxal** [comment]
yes very

> > > > > Asking because curious
> > > > 
> > > > 
> > > > about 10 minutes apparently
> > > 
> > > 
> > > @Lyxal what is your source?
> > 
> > 
> > The creator mentioned it in the MAWP discord
> 
> Woah! There's a discord?!?

yes very

**Comment by lyxal** [comment]
> yes very
> 
> > > > > > Asking because curious
> > > > > 
> > > > > 
> > > > > about 10 minutes apparently
> > > > 
> > > > 
> > > > @Lyxal what is your source?
> > > 
> > > 
> > > The creator mentioned it in the MAWP discord
> > 
> > 
> > Woah! There's a discord?!?
> 
> yes very

that's cool. can i have link?

**Comment by lyxal** [comment]
> > yes very
> > > > > > > Asking because curious
> > > > > > 
> > > > > > 
> > > > > > about 10 minutes apparently
> > > > > 
> > > > > 
> > > > > @Lyxal what is your source?
> > > > 
> > > > 
> > > > The creator mentioned it in the MAWP discord
> > > 
> > > 
> > > Woah! There's a discord?!?
> > 
> > 
> > yes very
> 
> that's cool. can i have link?

sorry, idk how to share from desktop

**Comment by lyxal** [comment]
> > yes very
> > 
> > > > > > > Asking because curious
> > > > > > 
> > > > > > 
> > > > > > about 10 minutes apparently
> > > > > 
> > > > > 
> > > > > @Lyxal what is your source?
> > > > 
> > > > 
> > > > The creator mentioned it in the MAWP discord
> > > 
> > > 
> > > Woah! There's a discord?!?
> > 
> > yes very
> 
> that's cool. can i have link?

Okay I got it

https://discord.gg/4YSDFCRnhY

**Comment by lyxal** [comment]
> > > yes very
> > > 
> > > > > > > > Asking because curious
> > > > > > > 
> > > > > > > 
> > > > > > > about 10 minutes apparently
> > > > > > 
> > > > > > 
> > > > > > @Lyxal what is your source?
> > > > > 
> > > > > 
> > > > > The creator mentioned it in the MAWP discord
> > > > 
> > > > 
> > > > Woah! There's a discord?!?
> > > 
> > > yes very
> > 
> > that's cool. can i have link?
> 
> Okay I got it
> 
> https://discord.gg/4YSDFCRnhY 

Thank you kayne, very cool

**Comment by lyxal** [comment]
> > > > yes very
> > > > 
> > > > > > > > > Asking because curious
> > > > > > > > 
> > > > > > > > 
> > > > > > > > about 10 minutes apparently
> > > > > > > 
> > > > > > > 
> > > > > > > @Lyxal what is your source?
> > > > > > 
> > > > > > 
> > > > > > The creator mentioned it in the MAWP discord
> > > > > 
> > > > > 
> > > > > Woah! There's a discord?!?
> > > > 
> > > > yes very
> > > 
> > > that's cool. can i have link?
> > 
> > Okay I got it
> > 
> > https://discord.gg/4YSDFCRnhY 
> 
> Thank you kayne, very cool 

No worries buddy

**Comment by lyxal** [comment]
This never did get implemented, did it.

**Comment by kirisoraa** [comment]
@Lyxal I... yeah, no. Maybe if I get the sudden urge to develop MAWP again after 3 years :D

**Comment by lyxal** [comment]
Lol
